name:                restartable
version:             0.1.0.0
github:              "mjgajda/restartable"
license:             BSD3
author:              "Michał J. Gajda"
maintainer:          "mjgajda@migamake.com"
copyright:           "'2020"

extra-source-files:
- README.md
- ChangeLog.md

synopsis: Minimal live coding library for model-view-event-update applications.
description: |
  Minimal live coding library.
  It can store model of the model-view-event-update applications.
  It uses `FromJSON` and `ToJSON` with default value
  for absent data elements, and `Generic` parser otherwise:
  > import Initially(initially, Initial)
  > data MyModel = Model { timestamp :: UTCTime }
  > instance FromJSON MyModel where
  >   parseJSON = initially myDefaultValue
  > instance Initial MyModel
  > 
  > main = restartable 

  Please see the README on GitHub at <https://github.com/mjgajda/restartable#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - optics # unused?
  - mtl
  - linear
  - aeson
  - scientific
  - text
  - vector
  - bytestring
  - unordered-containers
  - unix

